#上传下载限制
#总文件大小不能超过128千字节。
#多部分/表单数据不能超过128千字节
spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      # 激活配置
  profiles:
    active: dev
# sql版本管理
flyway:
  enabled: false

pg-db:
  schema: s_yuan

storage:
  upload-dir: xiazai

mybatis:
  mapper-locations: classpath:/mappers/*/*.xml
#knife4j:
#  enable: true
#  documents:
#    -
#      group: GROUP_1:yuan
#      name: 协作文档
#      locations: classpath:md/*
#    - group: GROUP_2:山西互联网医院
#      name: 协作文档
#      locations: classpath:ih_md/*
#  setting:
#    enableSwaggerModels: true
#    swaggerModelName: 实体类列表
#    enableDocumentManage: true
#    enableReloadCacheParameter: true
#    enableHostText: https://sxapi.xinzhili.cn
#    enableVersion: true
#    enableHost: true
#    enableRequestCache: true
#    enableFilterMultipartApis: false
#    enableFilterMultipartApiMethodType: POST
#    language: zh-CN
#  cors: true
#  production: false
#  basic:
#    enable: false
#    username: test
#    password: 123

---
spring:
  profiles: dev
  # 数据源
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/dev
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      pool-prepared-statements: true
      max-open-prepared-statements: 100
      connection-init-sql: "SET search_path TO ${pg-db.schema}"
server:
    port: 9099



---
spring:
  profiles: test
  server:
    port: 9100

---

spring:
  profiles: prod
  server:
    port: 9101

